# Generated by Django 5.2.5 on 2025-12-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_principal', models.CharField(max_length=150, verbose_name='Título principal')),
                ('subtitulo', models.TextField(blank=True, verbose_name='Subtítulo / descripción')),
                ('imagen_fondo', models.ImageField(blank=True, null=True, upload_to='cms/hero/', verbose_name='Imagen de fondo del hero')),
                ('texto_boton', models.CharField(blank=True, max_length=50, verbose_name='Texto del botón principal')),
                ('url_boton', models.CharField(blank=True, max_length=255, verbose_name='URL del botón principal')),
                ('mostrar_boton', models.BooleanField(default=True, verbose_name='Mostrar botón principal')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='TikTok')),
                ('whatsapp_url', models.URLField(blank=True, verbose_name='WhatsApp')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contenido de la página de inicio',
                'verbose_name_plural': 'Contenido de la página de inicio',
            },
        ),
    ]
