# Generated by Django 5.2.5 on 2025-12-02 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion_emocional', models.TextField(help_text='Descripción desde el punto de vista emocional o conceptual.')),
                ('terminos_tecnicos', models.TextField(help_text='Descripción técnica (tamaño, técnica, resolución, formato, etc.).')),
                ('tiempo_produccion', models.CharField(help_text="Tiempo estimado de producción (ej: '10 horas', '3 días').", max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio en dólares o pesos (según definas en el informe).', max_digits=10)),
                ('imagen_principal', models.ImageField(blank=True, help_text='Imagen principal de la obra.', null=True, upload_to='obras/')),
                ('en_stock', models.BooleanField(default=True, help_text='Indica si la obra está disponible para la venta.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se registró la obra en el sistema.')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obras', to='obras.categoria')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
