# Generated by Django 5.2.5 on 2025-12-02 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='obra',
            options={'ordering': ['-destacada', 'orden', '-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='obra',
            name='destacada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='obra',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador (solo visible en el Panel)'), ('publicada', 'Publicada (visible en el catálogo)')], default='publicada', max_length=20),
        ),
        migrations.AddField(
            model_name='obra',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Permite ordenar obras manualmente desde el panel.'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras', to='obras.categoria'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='descripcion_emocional',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='en_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='obras/'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='obra',
            name='terminos_tecnicos',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='tiempo_produccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='ObraImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_extra', to='obras.obra')),
            ],
        ),
    ]
